### ISSUE TITLE
Only `exec.go` gets generated

### ISSUE THREAD

**Issue by pojntfx** [danielvladco/go-proto-gql#10]
In my simple example gRPC service (see [this repo](https://github.com/pojntfx/grpc-go-math)), I'm trying to make use of this library. However, after using it as specified with the following go generate instruction:

```bash
//go:generate bash -c "protoc --go_out=plugins=grpc,paths=source_relative:../ --gqlgencfg_out=paths=source_relative:../ --gql_out=svcdir=true,paths=source_relative:../ --gogqlgen_out=paths=source_relative,gogoimport=false:../ -I=../ -I=/usr/local/include -I=`go list -m -f \"{{.Dir}}\" github.com/danielvladco/go-proto-gql/pb` ../proto/math.proto"
```
I try to generate the files for `gqlgen`:

```bash
[pojntfx@thinkpadx1c3 grpc-go-math]$ tree lib/proto/
lib/proto/
└── math.proto

0 directories, 1 file
[pojntfx@thinkpadx1c3 grpc-go-math]$ go generate ./...
go: finding github.com/pojntfx/grpc-go-math/lib latest
go: finding github.com/pojntfx/grpc-go-math/lib/proto latest
[pojntfx@thinkpadx1c3 grpc-go-math]$ tree lib/proto/
lib/proto/
├── math.gqlgen.pb.go
├── math.gqlgen.pb.yml
├── math.pb.go
├── math.pb.graphqls
└── math.proto

0 directories, 5 files
[pojntfx@thinkpadx1c3 grpc-go-math]$ cd lib/proto/
[pojntfx@thinkpadx1c3 proto]$ go run github.com/99designs/gqlgen -v -c ./math.gqlgen.pb.yml 
[pojntfx@thinkpadx1c3 proto]$ tree .
.
├── exec.go
├── math.gqlgen.pb.go
├── math.gqlgen.pb.yml
├── math.pb.go
├── math.pb.graphqls
└── math.proto

0 directories, 6 files
```

As you can see, only the `exec.go` file gets generated; `models.go` etc. is missing. Here is the `math.gqlgen.pb.yml` (which looks fine to me):

```yaml
schema:
- math.pb.graphqls
exec:
  filename: exec.go
model:
  filename: models.go
models:
  Int64:
    model:
    - github.com/danielvladco/go-proto-gql/pb.Int64
  MathAddArgsInput:
    model:
    - github.com/pojntfx/grpc-go-math/lib/proto.MathAddArgs
  MathAddReply:
    model:
    - github.com/pojntfx/grpc-go-math/lib/proto.MathAddReply
  MathSubtractArgsInput:
    model:
    - github.com/pojntfx/grpc-go-math/lib/proto.MathSubtractArgs
  MathSubtractReply:
    model:
    - github.com/pojntfx/grpc-go-math/lib/proto.MathSubtractReply
```

The following proto is the basis:

```bash
syntax = "proto3";

package math;
import "gql.proto";
option go_package = "github.com/pojntfx/grpc-go-math/lib/proto";

// Service math adds and subtracts numbers
service Math {
  rpc Add(MathAddArgs) returns (MathAddReply) {
    option (gql.rpc_type) = QUERY;
  };
  rpc Subtract(MathSubtractArgs) returns (MathSubtractReply) {
    option (gql.rpc_type) = QUERY;
  };
}

// MathAddArgs are the arguments for an addition
message MathAddArgs {
  int64 First = 1;
  int64 Second = 2;
}

// MathAddReply is the reply for an addition
message MathAddReply { int64 Result = 3; }

// MathSubtractArgs are the arguments for a subtraction
message MathSubtractArgs {
  int64 First = 1;
  int64 Second = 2;
}

// MathSubtractReply is the reply for a subtraction
message MathSubtractReply { int64 Result = 3; }
```

The generated `.graphqls` looks fine to me as well:

```bash
# Code generated by protoc-gen-gogql. DO NOT EDIT
# source: proto/math.proto

directive @Math(name: String) on FIELD_DEFINITION

scalar Int64

input MathAddArgsInput {
	first: Int64  
	second: Int64  
}

input MathSubtractArgsInput {
	first: Int64  
	second: Int64  
}

type MathAddReply {
	result: Int64 
}

type MathSubtractReply {
	result: Int64 
}

type Query {
	mathAdd(in: MathAddArgsInput): MathAddReply @Math
	mathSubtract(in: MathSubtractArgsInput): MathSubtractReply @Math
}
```

To summarize, it appears as though only the `exec.go` file gets generated; this however is not sufficient enough to build an actual GraphQL server. I'm still quite new to Golang, so there might be something obvious wrong here; sorry if that is the case.
